"""initial schema

Revision ID: 2b9aba54f861
Revises: 
Create Date: 2026-07-28 20:04:22.259157
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '2b9aba54f861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentprofile',
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('agent_name')
    )
    op.create_table('brief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('dropped_attributes', sa.JSON(), nullable=True),
    sa.Column('corpus_snapshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corpusref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('segment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corpusref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corpusref_source_handle'), ['source_handle'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpusref_source_id'), ['source_id'], unique=False)

    op.create_table('escalation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licence',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('licensor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('licensor_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signed_doc_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessionlogentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessionlogentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessionlogentry_session_id'), ['session_id'], unique=False)

    op.create_table('asset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permalink', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('licence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('context_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('review_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['licence_id'], ['licence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_sha256'), ['sha256'], unique=False)

    op.create_table('concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gate_result', sa.JSON(), nullable=True),
    sa.Column('reroll_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['brief.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('personalisation_zones', sa.JSON(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('complexity_band', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starting_price_aed', sa.Float(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.ForeignKeyConstraint(['photo_asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('product_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_ar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_ar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starting_price_aed', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['spec.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_product_code'), ['product_code'], unique=False)

    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['brief.id'], ),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['spec.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_product_code'))

    op.drop_table('product')
    op.drop_table('spec')
    op.drop_table('concept')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_sha256'))
        batch_op.drop_index(batch_op.f('ix_asset_origin'))

    op.drop_table('asset')
    with op.batch_alter_table('sessionlogentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessionlogentry_session_id'))

    op.drop_table('sessionlogentry')
    op.drop_table('milestone')
    op.drop_table('licence')
    op.drop_table('escalation')
    with op.batch_alter_table('corpusref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpusref_source_id'))
        batch_op.drop_index(batch_op.f('ix_corpusref_source_handle'))

    op.drop_table('corpusref')
    op.drop_table('brief')
    op.drop_table('agentprofile')
    # ### end Alembic commands ###
